# 기존 노드들 임포트
from .seed_wildcard import NODE_CLASS_MAPPINGS as MAP1, NODE_DISPLAY_NAME_MAPPINGS as NAME1
from .seed_wildcard_lora import NODE_CLASS_MAPPINGS as MAP2, NODE_DISPLAY_NAME_MAPPINGS as NAME2
from .seed_generator_min import NODE_CLASS_MAPPINGS as MAP3, NODE_DISPLAY_NAME_MAPPINGS as NAME3

# [추가됨] 예전에 만드신 노드들 임포트
from .resize_by_scale import NODE_CLASS_MAPPINGS as MAP4, NODE_DISPLAY_NAME_MAPPINGS as NAME4
from .dynamic_text_concatenate import NODE_CLASS_MAPPINGS as MAP5, NODE_DISPLAY_NAME_MAPPINGS as NAME5

# 모든 딕셔너리 병합 (MAP1 ~ MAP5)
NODE_CLASS_MAPPINGS = {**MAP1, **MAP2, **MAP3, **MAP4, **MAP5}
NODE_DISPLAY_NAME_MAPPINGS = {**NAME1, **NAME2, **NAME3, **NAME4, **NAME5}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']